In [41]:
import pymysql
connection = pymysql.connect(host='mydbm.chhjs88knp6j.us-west-1.rds.amazonaws.com',
                             user='admin',
                             password='mmiikkoo',
                             database='MYDBM',
                             
                            autocommit=True)
cursor=connection.cursor()
#Connector

In [3]:
import numpy as np

In [4]:
pwd="home"

In [116]:
cursor.execute("insert into table pwd values (0, 'home' )")

1

In [124]:
cursor.execute("select wd from pwd")
result=cursor.fetchall()
x=list(result)
y=x[0]
print(y[0])

home

In [136]:
cursor.execute("SHOW TABLES")
#ursor.execute("select * from  Directory_Organizer")
#cursor.execute("select wd from pwd")
#rsor.execute("select * from Files_Locator")
#rsor.execute("delete from Files_Locator where parent_dir='home'")
#cursor.execute("select * from partitions")
#cursor.execute("drop table CrimeO")
result=cursor.fetchall()                                      #Fetch out all the results through this
print("\n")
x= list(result)
s = [[str(e) for e in row] for row in x]                     #Pretty printer
lens = [max(map(len, col)) for col in zip(*s)]
fmt = '\t'.join('{{:{}}}'.format(x) for x in lens)
table = [fmt.format(*row) for row in s]
print('\n'.join(table))

Directory_Organizer
Files_Locator
pwd

In [109]:
cursor.execute("select* from Directory_Organizer")

5

In [89]:
for i in range(10):
    cursor.execute("drop table CrimeO"+str(i))

In [77]:
cursor.execute("Select parent_dir from Files_Locator where child_file='crimeo'")
result=cursor.fetchall()
result=list(result)
a=[]
for i in range(len(result)):
    result[i]=list(result[i])
    x=result[i]
    a.append(x[0])

[['Sachin'], ['user'], ['home'], ['home'], ['home'], ['home']]
['Sachin', 'user', 'home', 'home', 'home', 'home']

In [65]:
for i in range(8):
    cursor.execute("drop table CrimeO"+str(i))

In [66]:
cursor.execute("drop table CRIMEO_PARTITIONS")

0

In [137]:
cursor.execute("Create Table Directory_Organizer(parent_dir varchar(200), child_dir varchar(200))")

OperationalError: (1050, "Table 'Directory_Organizer' already exists")

In [138]:
cursor.execute("Create Table Files_Locator(parent_dir varchar(200), child_file varchar(200))")

OperationalError: (1050, "Table 'Files_Locator' already exists")

In [130]:
cursor.execute("Insert into Directory_Organizer values ('home','user')")
cursor.execute("Insert into Directory_Organizer values ('user','Sachin')")
pwd="home"

In [152]:
cursor.execute("Insert into Files_Locator values ('Sachin','CrimeP')")
cursor.execute("Insert into Files_Locator values ('Sachin','CrimeO')")

1

In [40]:
cursor.execute("Create Table partitions(serial_no int, table_name varchar(200))")

0

In [19]:
def mkdir(dir_name):
    Stringify="Insert into Directory_Organizer values ('"+pwd+"','"+dir_name+"')"
    cursor.execute(Stringify)

In [20]:
def ls(dir_name):
    print("+---------------------------+---------------------------+")
    print("|File Name------------------|------------------File Type|")
    print("+---------------------------+---------------------------+")
    ls_one(dir_name)
    
    ls_two(dir_name)

In [21]:
def ls_one(dir_name):
    Stringify="select child_dir from Directory_Organizer where parent_dir='"+dir_name+"'"
    cursor.execute(Stringify)
    result=cursor.fetchall()                                      #Fetch out all the results through this
    print("\n")
    x= list(result)
    s = [[str(e) for e in row] for row in x]                     #Pretty printer
    lens = [max(map(len, col)) for col in zip(*s)]
    fmt = '\t'.join('{{:{}}}'.format(x) for x in lens)
    table = [fmt.format(*row) for row in s]
    for i in range(len(table)):
        print(table[i]+"-------------------------------Directory")
    length=len(table)
    if(length==0):
        print("No Directories in the current directory")

In [22]:
def ls_two(dir_name):
    Stringify="select child_file from Files_Locator where parent_dir='"+dir_name+"'"
    cursor.execute(Stringify)
    result=cursor.fetchall()                                      #Fetch out all the results through this
    print("\n")
    x= list(result)
    s = [[str(e) for e in row] for row in x]                     #Pretty printer
    lens = [max(map(len, col)) for col in zip(*s)]
    fmt = '\t'.join('{{:{}}}'.format(x) for x in lens)
    table = [fmt.format(*row) for row in s]
    for i in range(len(table)):
        print(table[i]+"-------------------------------------------File")
    length=len(table)
    if(length==0):
        print("No Files in the current directory")

In [23]:
ls("home")

+---------------------------+---------------------------+
|File Name------------------|------------------File Type|
+---------------------------+---------------------------+


user-------------------------------Directory


No Files in the current directory

In [ ]:
def rmall(filename,totalpart):
    for i in range(totalpart):
        stringy=str(filename)+str(i)
        rm(stringy)
    stringy2=str(filename)+"_PARTITIONS"
    rm(stringy2)
    print("Successfully Deleted the data pertaining to "+filename)

In [24]:
def rm(filename):
    Stringify="Delete from Files_Locator where child_file='"+filename+"'"
    cursor.execute(Stringify)
    ##To Implement the deletion Implementation as well in here
    #print("Successfully Deleted the file "+filename+" and all its partitions")

In [16]:
rmall("CrimeO")

Successfully Deleted the data pertaining to CrimeO

In [25]:
def cd(newdir):
    global pwd
    if newdir=="..":
        if pwd=='home':
            print("This is the home directory so can't go above this")
        else:
            Stringify="select parent_dir from Directory_Organizer where child_dir='"+pwd+"'"
            cursor.execute(Stringify)
            result=cursor.fetchall()                                      #Fetch out all the results through this
        #print("\n")
            x= list(result)
            s = [[str(e) for e in row] for row in x]                     #Pretty printer
            lens = [max(map(len, col)) for col in zip(*s)]
            fmt = '\t'.join('{{:{}}}'.format(x) for x in lens)
            table = [fmt.format(*row) for row in s]
            pwd=table[0]
        
    else:
        Stringify="select child_dir from Directory_Organizer where child_dir='"+newdir+"'"
        cursor.execute(Stringify)
        result=cursor.fetchall()                                      #Fetch out all the results through this
        #print("\n")
        x= list(result)
        s = [[str(e) for e in row] for row in x]                     #Pretty printer
        lens = [max(map(len, col)) for col in zip(*s)]
        fmt = '\t'.join('{{:{}}}'.format(x) for x in lens)
        table = [fmt.format(*row) for row in s]
        if newdir in table:
            pwd=newdir
        else:
            print("Invalid Directory")

NameError: name 'pwd' is not defined

In [212]:
cd("..")

In [217]:
def put(filename,k): # k is the partitions and filename is the file being given to us
    dataframe=pd.read_csv(filename,encoding='unicode_escape')
    df=pd.DataFrame(data)
    df=df.rename(columns={'AREA ':'AREA_'})
    df=df.rename(columns={'Part_1-2':'Part_1'})
    dd=list(df.columns.values)
    df=df.replace("None","NULL")
    #print(dd)
    df=df.drop(['Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30', 'Unnamed: 31', 'Unnamed: 32'], axis=1)
    df = df.where((pd.notnull(df)), None)    
    N_PARTITIONS=k
    np.random.seed(2)
    permuted_indices = np.random.permutation(len(df))
    dfs=[]

    for i in range(N_PARTITIONS):
        dfs.append(df.iloc[permuted_indices[i::N_PARTITIONS]])
    for i in range(k):
        csv_to_sql(dfs[i],i)

In [219]:
def csv_to_sql(dataframe,i):## filename,i):
#    dataframe=pd.read_csv(filename,encoding='unicode_escape')
#    df=pd.DataFrame(data)
#    df=df.rename(columns={'AREA ':'AREA_'})
#    df=df.rename(columns={'Part_1-2':'Part_1'})
#    dd=list(df.columns.values)
#    df=df.replace("None","NULL")
#    print(dd)
#    df=df.drop(['Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30', 'Unnamed: 31', 'Unnamed: 32'], axis=1)
#    df = df.where((pd.notnull(df)), None)
    df=dataframe
    cursor.execute("CREATE TABLE CrimeO"+str(i)+"(DR_NO varchar(50), Date_Reported datetime, Date_Occurance datetime, Time_Occurance  varchar(50), Area varchar(50), Area_Name varchar(50), Dist_No varchar(20), Part12 int, Crimes_Committed varchar(50), Crimecodedesc varchar(100), mocodes varchar(50), victime_age  varchar(50), vict_sex varchar(20), vict_desc varchar(20), premis_cd varchar(20), premis_desc varchar(50),weapon varchar(30),weapondesc varchar(50), status varchar(20), status_desc varchar(50), crm1  varchar(50),crm2  varchar(50),crm3  varchar(50), crm4  varchar(50), location varchar(100),street varchar(50),latitude decimal(9,6),longitude decimal(8,6))")
    #print(df)
    for row in df.itertuples():
        try:
        #print(row.DR_NO)
        #cursor.execute("CREATE TABLE CrimeO(DR_NO varchar(50), Date_Reported datetime, Date_Occurance datetime, Time_Occurance  varchar(50), Area varchar(50), Area_Name varchar(50), Dist_No varchar(20), Part12 int, Crimes_Committed varchar(50), Crimecodedesc varchar(100), mocodes varchar(50), victime_age  varchar(50), vict_sex varchar(20), vict_desc varchar(20), premis_cd varchar(20), premis_desc varchar(50),weapon varchar(30),weapondesc varchar(50), status varchar(20), status_desc varchar(50), crm1  varchar(50),crm2  varchar(50),crm3  varchar(50), crm4  varchar(50), location varchar(100),street varchar(50),latitude decimal(9,6),longitude decimal(8,6))")
            sequences="Insert into CrimeO"+str(i)+" values('"+str(row.DR_NO)+"','"+str(row.Date_Rptd)+"','"+str(row.DATE_OCC)+"',"+str(row.TIME_OCC)+","+str(row.AREA_)+",'"+str(row.AREA_NAME)+"','"+str(row.Rpt_Dist_No)+"',"+str(row.Part_1)+",'"+str(row.Crm_Cd)+"','"+str(row.Crm_Cd_Desc)+"','"+str(row.Mocodes)+"','"+str(row.Vict_Age)+"','"+str(row.Vict_Sex)+"','"+str(row.Vict_Descent)+"','"+str(row.Premis_Cd)+"','"+str(row.Premis_Desc)+"','"+str(row.Weapon_Used_Cd)+"','"+str(row.Weapon_Desc)+"','"+str(row.Status)+"','"+str(row.Status_Desc)+"','"+str(row.Crm_Cd1)+"','"+str(row.Crm_Cd2)+"','"+str(row.Crm_Cd3)+"','"+str(row.Crm_Cd4)+"','"+str(row.LOCATION)+"','"+str(row.Cross_Street)+"',"+str(row.LAT)+","+str(row.LON)+")"
            cursor.execute(sequences)                        #SAMPLE EXECUTIONS
            #print("\n")
            connection.commit()
            
        #    print(sequences)
        #print('\n')
        except:
            print("Some problem")
        
    print("I am done here \n")

In [216]:
cursor.execute("drop table CrimeO0")

0

In [220]:
put("Crime_Data_from_2010_to_2019.csv",1000)

Some problem
I am done here

Some problem
Some problem
Some problem
Some problem
I am done here

Some problem
Some problem
Some problem
Some problem
I am done here

Some problem
Some problem
I am done here

Some problem
Some problem
Some problem
I am done here

Some problem
Some problem
I am done here

Some problem
Some problem
I am done here

I am done here

Some problem
Some problem
I am done here

Some problem
Some problem
Some problem
Some problem
Some problem
I am done here

Some problem
I am done here

Some problem
Some problem
I am done here

Some problem
Some problem
Some problem
I am done here

Some problem
Some problem
Some problem
Some problem
I am done here

Some problem
Some problem
Some problem
I am done here

I am done here

Some problem
Some problem
I am done here

Some problem
I am done here

Some problem
I am done here

Some problem
I am done here

Some problem
Some problem
I am done here

Some problem
Some problem
I am done here

I am done here

Some problem
Some problem
I am done here

Some problem
Some problem
Some problem
I am done here

Some problem
Some problem
Some problem
I am done here

Some problem
Some problem
Some problem
Some problem
I am done here

Some problem
I am done here

Some problem
I am done here

I am done here

Some problem
Some problem
I am done here

Some problem
Some problem
Some problem
Some problem
I am done here

I am done here

Some problem
Some problem
Some problem
Some problem
I am done here

Some problem
I am done here

Some problem
Some problem
Some problem
I am done here

Some problem
I am done here

Some problem
Some problem
Some problem
I am done here

Some problem
I am done here

Some problem
I am done here

Some problem
Some problem
Some problem
I am done here

Some problem
I am done here

Some problem
Some problem
I am done here

Some problem
Some problem
I am done here

Some problem
Some problem
I am done here

Some problem
Some problem
Some problem
Some problem
I am done here

Some problem
Some problem
I am done here

I am done here

Some problem
Some problem
Some problem
Some problem
I am done here

Some problem
Some problem
Some problem
I am done here

Some problem
I am done here

Some problem
Some problem
Some problem
I am done here

Some problem
I am done here

Some problem
Some problem
I am done here

Some problem
Some problem
I am done here

Some problem
I am done here

Some problem
I am done here

Some problem
I am done here

Some problem
Some problem
Some problem
I am done here

Some problem
Some problem
Some problem
I am done here

Some problem
Some problem
Some problem
I am done here

Some problem
I am done here

Some problem
I am done here

Some problem
I am done here

Some problem
Some problem
Some problem
I am done here

Some problem
Some problem
I am done here

Some problem
I am done here

Some problem
Some problem
Some problem
I am done here

Some problem
I am done here

Some problem
I am done here

I am done here

Some problem
Some problem
Some problem
Some problem
I am done here

Some problem
Some problem
I am done here

Some problem
Some problem
Some problem
Some problem
I am done here

Some problem
Some problem
Some problem
I am done here

Some problem
Some problem
I am done here

Some problem
Some problem
Some problem
Some problem
I am done here

Some problem
Some problem
Some problem
I am done here

Some problem
Some problem
Some problem
I am done here

Some problem
I am done here

I am done here

Some problem
Some problem
Some problem
Some problem
I am done here

Some problem
Some problem
I am done here

Some problem
Some problem
I am done here

Some problem
I am done here

Some problem
I am done here

Some problem
I am done here

Some problem
Some problem
I am done here

Some problem
I am done here

Some problem
Some problem
Some problem
Some problem
I am done here

Some problem
Some problem
Some problem
Some problem
I am done here

Some problem
I am done here

Some problem
Some problem
I am done here

Some problem
Some problem
Some problem
I am done here

Some problem
Some problem
Some problem
I am done here

I am done here

Some problem
Some problem
Some problem
Some problem
I am done here

Some problem
Some problem
Some problem
I am done here

Some problem
Some problem
I am done here

Some problem
Some problem
I am done here

Some problem
Some problem
I am done here

Some problem
I am done here

Some problem
Some problem
Some problem
Some problem
I am done here

Some problem
Some problem
I am done here

Some problem
Some problem
I am done here

Some problem
Some problem
Some problem
Some problem
Some problem
I am done here

Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
I am done here

Some problem
Some problem
Some problem
Some problem
I am done here

Some problem
I am done here

Some problem
I am done here

Some problem
Some problem
Some problem
I am done here

Some problem
Some problem
Some problem
Some problem
I am done here

I am done here

Some problem
I am done here

Some problem
I am done here

Some problem
Some problem
Some problem
I am done here

I am done here

Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
I am done here

Some problem
Some problem
Some problem
Some problem
Some problem
I am done here

Some problem
Some problem
Some problem
I am done here

Some problem
Some problem
Some problem
Some problem
I am done here

I am done here

Some problem
Some problem
Some problem
Some problem
Some problem
I am done here

I am done here

Some problem
I am done here

Some problem
I am done here

Some problem
I am done here

Some problem
Some problem
I am done here

I am done here

Some problem
Some problem
I am done here

Some problem
Some problem
I am done here

Some problem
Some problem
Some problem
I am done here

Some problem
Some problem
Some problem
I am done here

Some problem
Some problem
I am done here

Some problem
I am done here

Some problem
Some problem
I am done here

Some problem
Some problem
I am done here

Some problem
Some problem
Some problem
Some problem
Some problem
I am done here

Some problem
Some problem
Some problem
I am done here

Some problem
I am done here

Some problem
Some problem
Some problem
Some problem
I am done here

Some problem
Some problem
I am done here

I am done here

Some problem
Some problem
Some problem
I am done here

Some problem
Some problem
I am done here

Some problem
Some problem
Some problem
Some problem
I am done here

Some problem
I am done here

Some problem
Some problem
I am done here

Some problem
Some problem
I am done here

Some problem
Some problem
I am done here

I am done here

Some problem
Some problem
Some problem
I am done here

Some problem
I am done here

Some problem
Some problem
Some problem
Some problem
I am done here

Some problem
Some problem
Some problem
I am done here

Some problem
Some problem
I am done here

Some problem
I am done here

Some problem
Some problem
I am done here

Some problem
Some problem
Some problem
I am done here

Some problem
Some problem
I am done here

Some problem
I am done here

Some problem
Some problem
Some problem
I am done here

Some problem
Some problem
I am done here

Some problem
I am done here

Some problem
I am done here

Some problem
Some problem
Some problem
Some problem
I am done here

Some problem
I am done here

Some problem
I am done here

Some problem
I am done here

Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
I am done here

Some problem
Some problem
I am done here

Some problem
Some problem
Some problem
I am done here

Some problem
Some problem
Some problem
Some problem
I am done here

Some problem
Some problem
Some problem
Some problem
Some problem
I am done here

I am done here

Some problem
Some problem
I am done here

Some problem
I am done here

Some problem
Some problem
I am done here

Some problem
Some problem
Some problem
I am done here

Some problem
Some problem
I am done here

Some problem
Some problem
I am done here

Some problem

Some problem
Some problem
I am done here

Some problem
Some problem
Some problem
I am done here

Some problem
I am done here

I am done here

Some problem
Some problem
I am done here

Some problem
I am done here

Some problem
Some problem
I am done here

Some problem
Some problem
I am done here

Some problem
Some problem
Some problem
Some problem
I am done here

I am done here

Some problem
I am done here

Some problem
Some problem
Some problem
I am done here

Some problem
I am done here

Some problem
Some problem
Some problem
I am done here

Some problem
Some problem
Some problem
I am done here

Some problem
Some problem
I am done here

Some problem
Some problem
Some problem
Some problem
I am done here

Some problem
I am done here

I am done here

Some problem
Some problem
I am done here

Some problem
Some problem
Some problem
Some problem
I am done here

Some problem
Some problem
Some problem
I am done here

Some problem
I am done here

Some problem
Some problem
Some problem
I am done here

Some problem
Some problem
Some problem
Some problem
I am done here

Some problem
I am done here

Some problem
Some problem
Some problem
Some problem
I am done here

Some problem
Some problem
Some problem
I am done here

Some problem
I am done here

Some problem
Some problem
I am done here

Some problem
Some problem
Some problem
Some problem
I am done here

Some problem
Some problem
I am done here

Some problem
Some problem
I am done here

Some problem
Some problem
Some problem
I am done here

I am done here

Some problem
Some problem
I am done here

Some problem
I am done here

I am done here

Some problem
Some problem
Some problem
Some problem
I am done here

Some problem
Some problem
Some problem
I am done here

Some problem
Some problem
Some problem
Some problem
Some problem
I am done here

Some problem
Some problem
I am done here

Some problem
I am done here

I am done here

Some problem
Some problem
Some problem
I am done here

I am done here

Some problem
Some problem
Some problem
I am done here

Some problem
Some problem
Some problem
I am done here

Some problem
I am done here

Some problem
Some problem
I am done here

Some problem
Some problem
I am done here

Some problem
Some problem
Some problem
Some problem
I am done here

Some problem
I am done here

Some problem
Some problem
I am done here

Some problem
Some problem
Some problem
I am done here

Some problem
Some problem
I am done here

Some problem
Some problem
Some problem
Some problem
Some problem
I am done here

Some problem
Some problem
Some problem
Some problem
Some problem
I am done here

Some problem
Some problem
Some problem
I am done here

Some problem
I am done here

I am done here

Some problem
Some problem
I am done here

Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
I am done here

Some problem
Some problem
I am done here

Some problem
I am done here

Some problem
I am done here

Some problem
I am done here

Some problem
Some problem
I am done here

Some problem
Some problem
I am done here

Some problem
Some problem
Some problem
Some problem
Some problem
I am done here

I am done here

Some problem
I am done here

Some problem
Some problem
I am done here

Some problem
Some problem
I am done here

Some problem
Some problem
Some problem
Some problem
Some problem
I am done here

Some problem
Some problem
Some problem
I am done here

I am done here

Some problem
I am done here

Some problem
I am done here

Some problem
I am done here

Some problem
Some problem
Some problem
I am done here

I am done here

Some problem
I am done here

Some problem
Some problem
Some problem
I am done here

Some problem
Some problem
Some problem
I am done here

Some problem
I am done here

Some problem
Some problem
Some problem
I am done here

Some problem
Some problem
I am done here

Some problem
I am done here

Some problem
Some problem
I am done here

Some problem
Some problem
Some problem
I am done here

Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
Some problem
I am done here

InterfaceError: (0, '')

In [28]:
import pandas as pd
data=pd.read_csv("Crime_Data_from_2010_to_2019.csv",encoding='unicode_escape')
CrimeO=pd.DataFrame(data)

In [29]:
dd=list(CrimeO.columns.values)     #SAMPLE CODE LINE
print(dd)

['DR_NO', 'Date_Rptd', 'DATE_OCC', 'TIME_OCC', 'AREA_', 'AREA_NAME', 'Rpt_Dist_No', 'Part_1-2', 'Crm_Cd', 'Crm_Cd_Desc', 'Mocodes', 'Vict_Age', 'Vict_Sex', 'Vict_Descent', 'Premis_Cd', 'Premis_Desc', 'Weapon_Used_Cd', 'Weapon_Desc', 'Status', 'Status_Desc', 'Crm_Cd1', 'Crm_Cd2', 'Crm_Cd3', 'Crm_Cd4', 'LOCATION', 'Cross_Street', 'LAT', 'LON', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30', 'Unnamed: 31', 'Unnamed: 32']

In [240]:
import pandas as pd
                                                                    #SAMPLE EXECUTIONS
data = pd.read_csv("sampler.csv", encoding= 'unicode_escape')
df = pd.DataFrame(data)

print(df)

   product_id product_name  price
0           1       Laptop    100
1           2       Mobile      2
2           3       Tablet      2
3           4      Monitor      3
4           5     Keyboard      4

In [236]:
cursor.execute("CREATE TABLE products(product_id int,product_name varchar(200),price int)")#SAMPLE EXECUTIONS

0

In [249]:
for row in df.itertuples():
    sequences="Insert into products values ("+str(row.product_id)+",'"+str(row.product_name)+"',"+str(row.price)+")"
    cursor.execute(sequences)                        #SAMPLE EXECUTIONS

In [2]:
import pandas as pd                                          #SAMPLE CODE LINE

In [3]:
dfm = pd.DataFrame({'A' : ['foo', 'bar', 'foo', 'bar',  'foo', 'bar', 'foo', 'foo']*2,
                      'B' : ['one', 'one', 'two', 'three', 'two', 'two', 'one', 'three']*2}) 
                                                                                                    #SAMPLE CODE LINE

In [6]:
import numpy as np
N_PARTITIONS=10
permuted_indices = np.random.permutation(len(dfm))
dfs=[]                                                                                      #SAMPLE CODE LINE

for i in range(N_PARTITIONS):
    dfs.append(dfm.iloc[permuted_indices[i::N_PARTITIONS]])

In [200]:
dfs[9]                                                     #SAMPLE CODE LINE

In [215]:
cursor.execute("show columns from CrimeO0")
#cursor.execute("select * from Directory_Organizer")
#cursor.execute("select * from Files_Locator")
#cursor.execute("select * from partitions")
#cursor.execute("drop table CrimeO0")
result=cursor.fetchall()                                      #Fetch out all the results through this
result=list(result)
for i in range(len(result)):
    print(result[i])

('DR_NO', 'varchar(50)', 'YES', '', None, '')
('Date_Reported', 'datetime', 'YES', '', None, '')
('Date_Occurance', 'datetime', 'YES', '', None, '')
('Time_Occurance', 'varchar(50)', 'YES', '', None, '')
('Area', 'varchar(50)', 'YES', '', None, '')
('Area_Name', 'varchar(50)', 'YES', '', None, '')
('Dist_No', 'varchar(20)', 'YES', '', None, '')
('Part12', 'int', 'YES', '', None, '')
('Crimes_Committed', 'varchar(50)', 'YES', '', None, '')
('Crimecodedesc', 'varchar(100)', 'YES', '', None, '')
('mocodes', 'varchar(50)', 'YES', '', None, '')
('victime_age', 'varchar(50)', 'YES', '', None, '')
('vict_sex', 'varchar(20)', 'YES', '', None, '')
('vict_desc', 'varchar(20)', 'YES', '', None, '')
('premis_cd', 'varchar(20)', 'YES', '', None, '')
('premis_desc', 'varchar(50)', 'YES', '', None, '')
('weapon', 'varchar(30)', 'YES', '', None, '')
('weapondesc', 'varchar(50)', 'YES', '', None, '')
('status', 'varchar(20)', 'YES', '', None, '')
('status_desc', 'varchar(50)', 'YES', '', None, '')
('crm1', 'varchar(50)', 'YES', '', None, '')
('crm2', 'varchar(50)', 'YES', '', None, '')
('crm3', 'varchar(50)', 'YES', '', None, '')
('crm4', 'varchar(50)', 'YES', '', None, '')
('location', 'varchar(100)', 'YES', '', None, '')
('street', 'varchar(50)', 'YES', '', None, '')
('latitude', 'decimal(9,6)', 'YES', '', None, '')
('longitude', 'decimal(8,6)', 'YES', '', None, '')

In [302]:
cursor.execute("show tables")
result=cursor.fetchall()
x=list(result)
s = [[str(e) for e in row] for row in x]                     #Pretty printer
lens = [max(map(len, col)) for col in zip(*s)]
fmt = '\t'.join('{{:{}}}'.format(x) for x in lens)
table = [fmt.format(*row) for row in s]
print('\n'.join(table))

CrimeO0
CrimeO1
CrimeO10
CrimeO100
CrimeO101
CrimeO102
CrimeO103
CrimeO104
CrimeO105
CrimeO106
CrimeO107
CrimeO108
CrimeO109
CrimeO11
CrimeO110
CrimeO111
CrimeO112
CrimeO113
CrimeO114
CrimeO115
CrimeO116
CrimeO117
CrimeO118
CrimeO119
CrimeO12
CrimeO120
CrimeO121
CrimeO122
CrimeO123
CrimeO124
CrimeO125
CrimeO126
CrimeO127
CrimeO128
CrimeO129
CrimeO13
CrimeO130
CrimeO131
CrimeO132
CrimeO133
CrimeO134
CrimeO135
CrimeO136
CrimeO137
CrimeO138
CrimeO139
CrimeO14
CrimeO140
CrimeO141
CrimeO142
CrimeO143
CrimeO144
CrimeO145
CrimeO146
CrimeO147
CrimeO148
CrimeO149
CrimeO15
CrimeO150
CrimeO151
CrimeO152
CrimeO153
CrimeO154
CrimeO155
CrimeO156
CrimeO157
CrimeO158
CrimeO159
CrimeO16
CrimeO160
CrimeO161
CrimeO162
CrimeO163
CrimeO164
CrimeO165
CrimeO166
CrimeO167
CrimeO168
CrimeO169
CrimeO17
CrimeO170
CrimeO171
CrimeO172
CrimeO173
CrimeO174
CrimeO175
CrimeO176
CrimeO177
CrimeO178
CrimeO179
CrimeO18
CrimeO180
CrimeO181
CrimeO182
CrimeO183
CrimeO184
CrimeO185
CrimeO186
CrimeO187
CrimeO188
CrimeO189
CrimeO19
CrimeO190
CrimeO191
CrimeO192
CrimeO193
CrimeO194
CrimeO195
CrimeO196
CrimeO197
CrimeO198
CrimeO199
CrimeO2
CrimeO20
CrimeO200
CrimeO201
CrimeO202
CrimeO203
CrimeO204
CrimeO205
CrimeO206
CrimeO207
CrimeO208
CrimeO209
CrimeO21
CrimeO210
CrimeO211
CrimeO212
CrimeO213
CrimeO214
CrimeO215
CrimeO216
CrimeO217
CrimeO218
CrimeO219
CrimeO22
CrimeO220
CrimeO221
CrimeO222
CrimeO223
CrimeO224
CrimeO225
CrimeO226
CrimeO227
CrimeO228
CrimeO229
CrimeO23
CrimeO230
CrimeO231
CrimeO232
CrimeO233
CrimeO234
CrimeO235
CrimeO236
CrimeO237
CrimeO238
CrimeO239
CrimeO24
CrimeO240
CrimeO241
CrimeO242
CrimeO243
CrimeO244
CrimeO245
CrimeO246
CrimeO247
CrimeO248
CrimeO249
CrimeO25
CrimeO250
CrimeO251
CrimeO252
CrimeO253
CrimeO254
CrimeO255
CrimeO256
CrimeO257
CrimeO258
CrimeO259
CrimeO26
CrimeO260
CrimeO261
CrimeO262
CrimeO263
CrimeO264
CrimeO265
CrimeO266
CrimeO267
CrimeO268
CrimeO269
CrimeO27
CrimeO270
CrimeO271
CrimeO272
CrimeO28
CrimeO29
CrimeO3
CrimeO30
CrimeO31
CrimeO32
CrimeO33
CrimeO34
CrimeO35
CrimeO36
CrimeO37
CrimeO38
CrimeO39
CrimeO4
CrimeO40
CrimeO41
CrimeO42
CrimeO43
CrimeO44
CrimeO45
CrimeO46
CrimeO47
CrimeO48
CrimeO49
CrimeO5
CrimeO50
CrimeO51
CrimeO52
CrimeO53
CrimeO54
CrimeO55
CrimeO56
CrimeO57
CrimeO58
CrimeO59
CrimeO6
CrimeO60
CrimeO61
CrimeO62
CrimeO63
CrimeO64
CrimeO65
CrimeO66
CrimeO67
CrimeO68
CrimeO69
CrimeO7
CrimeO70
CrimeO71
CrimeO72
CrimeO73
CrimeO74
CrimeO75
CrimeO76
CrimeO77
CrimeO78
CrimeO79
CrimeO8
CrimeO80
CrimeO81
CrimeO82
CrimeO83
CrimeO84
CrimeO85
CrimeO86
CrimeO87
CrimeO88
CrimeO89
CrimeO9
CrimeO90
CrimeO91
CrimeO92
CrimeO93
CrimeO94
CrimeO95
CrimeO96
CrimeO97
CrimeO98
CrimeO99
Directory_Organizer
Files_Locator
partitions
produc

In [276]:
cursor.execute("select count(*) from CrimeO0")
result=cursor.fetchall()                                      #Fetch out all the results through this
print("\n")
x= list(result)
s = [[str(e) for e in row] for row in x]                     #Pretty printer
lens = [max(map(len, col)) for col in zip(*s)]
fmt = '\t'.join('{{:{}}}'.format(x) for x in lens)
table = [fmt.format(*row) for row in s]
print('\n'.join(table))

1048

In [361]:
cursor.execute("show columns from CrimeO0")
#cursor.execute("select * from Directory_Organizer")
#cursor.execute("select * from Files_Locator")
#cursor.execute("select * from partitions")
#cursor.execute("drop table CrimeO0")
result=cursor.fetchall()                                      #Fetch out all the results through this
result=list(result)
summedup=[]
for i in range(len(result)):
    result[i]=list(result[i])
    x=result[i]
    summedup.append(x[0])

In [363]:
print(len(summedup))

28

In [342]:
def mapPartitions(Tablename,tofind,field):
    cursor.execute("select * from "+str(Tablename)+" where "+str(field)+" ='"+str(tofind)+"'")
#cursor.execute("select * from Directory_Organizer")
#cursor.execute("select * from Files_Locator")
#cursor.execute("select * from partitions")
#cursor.execute("drop table CrimeO0")
    result=cursor.fetchall()                                      #Fetch out all the results through this
    result=list(result)
    listener=[]
    for i in range(len(result)):
        #print(result[i])
        print('\n')
        listener.append(result[i])
    return(listener)

In [348]:
recorded=mapPartitions("CrimeO0","121200851","DR_NO")
print(len(recorded[0]))

28

In [349]:
def display_select_attributes(tablename,list_attr,tofind,field):
    list_final=[]
    record=searcher(tablename,tofind,field)
    for i in range(len(record)):
        list_final1=[]
        for j in range(len(record[i])):
            
            x=record[i]
            if(list_attr[j]==1):
                list_final1.append(x[j])
            else:
                pass
        list_final.append(list_final1)
    return list_final

In [374]:
listed=[1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
rex=display_select_attributes("CrimeO0",listed,"121200851","DR_NO")
x=rex[0]
print(x)
for j in range(len(x)):
    for i in range(len(listed)):            
        if(listed[i]==1):
            print(str(summedup[i])+":"+str(x[j]))

['121200851', '12']
DR_NO:121200851
Area:121200851
DR_NO:12
Area:12

In [330]:
print(returnedval)

[]

In [274]:
cursor.execute("select * from CrimeO0 limit 1")
result=cursor.fetchall()                                      #Fetch out all the results through this
print("\n")
x= list(result)
s = [[str(e) for e in row] for row in x]                     #Pretty printer
lens = [max(map(len, col)) for col in zip(*s)]
fmt = '\t'.join('{{:{}}}'.format(x) for x in lens)
table = [fmt.format(*row) for row in s]
print('\n'.join(table))

121200851	0000-00-00 00:00:00	0000-00-00 00:00:00	2300	12	77th Street	1258	2	626	INTIMATE PARTNER - SIMPLE ASSAULT	1203 0416 0429 1243 1813 2000 0444 0319	26	F	B	501.0	SINGLE FAMILY DWELLING	400.0	STRONG-ARM (HANDS, FIST, FEET OR BODILY FORCE)	IC	Invest Cont	626.0	None	None	None	100 W  78TH                         ST	None	33.968900	-99.999999

In [311]:
def reduce(tableoriginalname,tofind,field):
    cursor.execute("select * from "+str(tableoriginalname)+"_len")
    result=cursor.fetchall()
    result=list(result)
    result[0]=list(result[0])
    x=result[0]
    y=x[0]
    list_res=[]
    for i in range(250): #len(y)):
        Table="CrimeO"+str(i)
        mapPartitions(Table,tofind,field)

In [317]:
reduce("CrimeO","121200851","DR_NO")

('121200851', '0000-00-00 00:00:00', '0000-00-00 00:00:00', '2300', '12', '77th Street', '1258', 2, '626', 'INTIMATE PARTNER - SIMPLE ASSAULT', '1203 0416 0429 1243 1813 2000 0444 0319', '26', 'F', 'B', '501.0', 'SINGLE FAMILY DWELLING', '400.0', 'STRONG-ARM (HANDS, FIST, FEET OR BODILY FORCE)', 'IC', 'Invest Cont', '626.0', 'None', 'None', 'None', '100 W  78TH                         ST', 'None', Decimal('33.968900'), Decimal('-99.999999'))

In [296]:
def length_finder(tablename):
    cursor.execute("select count(*) from CrimeO0")
    result=cursor.fetchall()
    result=list(result)
    result[0]=list(result[0])
    x=result[0]
    y=x[0]
    return y

1048

In [323]:
def attributewisesearcher(attribute,Tablename,tofind,field):
    cursor.execute("select "+str(attribute)+" from "+str(Tablename)+" where "+str(field)+" ='"+str(tofind)+"'")
#cursor.execute("select * from Directory_Organizer")
#cursor.execute("select * from Files_Locator")
#cursor.execute("select * from partitions")
#cursor.execute("drop table CrimeO0")
    result=cursor.fetchall()                                      #Only displays a certain attribute
    result=list(result)
    for i in range(len(result)):
        print(result[i])
        print('\n')

In [17]:
def getpartitionlocations(Tablename):
    syntaxy="select partition_locations from "+str(Tablename)+"_PARTITIONS"
    cursor.execute(syntaxy)
    result=cursor.fetchall()
    x= list(result)
    s = [[str(e) for e in row] for row in x]                     #Pretty printer
    lens = [max(map(len, col)) for col in zip(*s)]
    fmt = '\t'.join('{{:{}}}'.format(x) for x in lens)
    table = [fmt.format(*row) for row in s]
    print('\n'.join(table))

In [20]:
getpartitionlocations("CRIMEO")

0  	794310
1  	489367
2  	87218
3  	389298
4  	838125
5  	325378
6  	63700
7  	450636
8  	223587
9  	170084
10 	927969
11 	896828
12 	377332
13 	771303
14 	70190
15 	333468
16 	119200
17 	467414
18 	694862
19 	227080
20 	497191
21 	362250
22 	513004
23 	316529
24 	309807
25 	465618
26 	602408
27 	547243
28 	97143
29 	667997
30 	640363
31 	172996
32 	965499
33 	656850
34 	148223
35 	931489
36 	615965
37 	882278
38 	766438
39 	575861
40 	462140
41 	127306
42 	694364
43 	596882
44 	58308
45 	274637
46 	665477
47 	643236
48 	83828
49 	996657
50 	107720
51 	941917
52 	465943
53 	114792
54 	217559
55 	151197
56 	41691
57 	862332
58 	504142
59 	403757
60 	477975
61 	920038
62 	913582
63 	453904
64 	378908
65 	895139
66 	906038
67 	727280
68 	359080
69 	887897
70 	104386
71 	338371
72 	992680
73 	819325
74 	161643
75 	83522
76 	865450
77 	881869
78 	789002
79 	450645
80 	921040
81 	663850
82 	475089
83 	736339
84 	209508
85 	668212
86 	453949
87 	101539
88 	853314
89 	772522
90 	136665
91 	662221
92 	691071
93 	787501
94 	279950
95 	346324
96 	563182
97 	728754
98 	796564
99 	774071
100	566173
101	599940
102	756747
103	712519
104	901565
105	881323
106	530549
107	116651
108	82194
109	184981
110	555836
111	876342
112	381215
113	694927
114	857046
115	210994
116	759946
117	384763
118	512773
119	596460
120	888618
121	384630
122	213286
123	908413
124	445434
125	56973
126	194001
127	811318
128	704713
129	908375
130	861591
131	480589
132	178232
133	322392
134	104398
135	12236
136	314067
137	864825
138	32509
139	980559
140	480199
141	811173
142	261346
143	639776
144	686629
145	286643
146	175325
147	461611
148	904776
149	197697
150	863289
151	635734
152	477208
153	437284
154	856754
155	80274
156	359660
157	190004
158	957402
159	361792
160	964137
161	461805
162	956666
163	192029
164	928775
165	333005
166	416819
167	473713
168	638625
169	472094
170	331291
171	412224
172	45913
173	219963
174	855484
175	366271
176	816162
177	380046
178	139442
179	117922
180	206135
181	360418
182	703590
183	972232
184	814420
185	786977
186	73860
187	507718
188	650882
189	186021
190	219042
191	564887
192	797883
193	926721
194	40566
195	65034
196	995793
197	745111
198	235719
199	644091
200	167975
201	989151
202	785218
203	873532
204	755515
205	133312
206	684379
207	571864
208	78647
209	847710
210	665033
211	661455
212	378405
213	514709
214	50660
215	589821
216	446055
217	441675
218	402905
219	790427
220	737588
221	230823
222	571261
223	298938
224	360091
225	802638
226	779876
227	835301
228	165478
229	543466
230	267648
231	352828
232	906086
233	202128
234	521870
235	839684
236	161203
237	354259
238	9641
239	82073
240	174409
241	840204
242	24870
243	866686
244	675258
245	770475
246	571184
247	551136
248	369630
249	779821
250	219841
251	842270
252	1202
253	548603
254	832382
255	47661
256	447104
257	291759
258	607985
259	180114
260	228110
261	766224
262	19530
263	621423
264	325776
265	324346
266	936920
267	508164
268	630484
269	476952
270	944417
271	410315
272	740009
273	103926
274	762819
275	390982
276	158210
277	970576
278	30946
279	276318
280	366731
281	685015
282	566586
283	146625
284	175541
285	167301
286	323784
287	779853
288	561218
289	731248
290	568008
291	1986
292	175774
293	371826
294	661118
295	963485
296	842923
297	662520
298	803920
299	425854
300	788214
301	993369
302	765561
303	444900
304	23350
305	854170
306	552426
307	925509
308	426167
309	452365
310	852211
311	292073
312	984887
313	91964
314	573248
315	299183
316	833738
317	424577
318	970642
319	771276
320	583891
321	315761
322	111137
323	598559
324	4759
325	346676
326	689739
327	753529
328	934314
329	934457
330	418029
331	259082
332	697071
333	794415
334	831208
335	352247
336	694368
337	998824
338	7040
339	175221
340	541258
341	606759
342	217234
343	148372
344	6239
345	958537
346	506755
347	314970
348	16956
349	778387
350	83190
351	609472
352	312918
353	400321
354	928938
355	11596
356	611697
357	251043
358	553562
359	741667
360	643028
361	223221
362	577247
363	897201
364	89392
365	794788
366	143760
367	344039
368	994931
369	233998
370	706518
371	228202
372	721439
373	415874
374	816858
375	981921
376	584718
377	940323
378	843419
379	601895
380	955699
381	246009
382	45291
383	81433
384	345643
385	67205
386	627472
387	557355
388	115240
389	230486
390	364850
391	311497
392	749692
393	340012
394	600926
395	762233
396	26019
397	422940
398	148487
399	849309
400	546717
401	399215
402	571191
403	954925
404	910160
405	529388
406	514208
407	490810
408	760350
409	417917
410	253993
411	335670
412	88281
413	652074
414	961515
415	767295
416	882905
417	4564
418	460216
419	234211
420	411718
421	747313
422	109931
423	479304
424	729751
425	200482
426	5002
427	35928
428	405137
429	19831
430	923295
431	314231
432	335531
433	109886
434	357310
435	655641
436	861009
437	739235
438	751996
439	215961
440	833894
441	560433
442	623506
443	118990
444	547268
445	698553
446	349709
447	932905
448	404612
449	546431
450	208568
451	758256
452	969003
453	383136
454	278587
455	163100
456	486403
457	202390
458	907183
459	531072
460	979912
461	955622
462	711800
463	331552
464	384437
465	963538
466	240558
467	976626
468	835294
469	874293
470	456775
471	824502
472	938139
473	218552
474	507705
475	269034
476	272721
477	232550
478	164958
479	959532
480	260027
481	311872
482	556700
483	663215
484	979092
485	540490
486	478539
487	948581
488	176983
489	942750
490	296556
491	541498
492	580933
493	359337
494	797460
495	478574
496	706735
497	720913
498	456673
499	161123
500	90574
501	863622
502	277663
503	489735
504	959000
505	270328
506	34893
507	872090
508	916693
509	711004
510	139090
511	515192
512	109465
513	696241
514	76389
515	791178
516	333501
517	183582
518	92401
519	159568
520	559673
521	382732
522	876005
523	44578
524	557535
525	265227
526	541249
527	219929
528	856986
529	386163
530	550901
531	249843
532	624128
533	950237
534	537789
535	939147
536	642537
537	717367
538	336381
539	878973
540	652333
541	966436
542	372778
543	971409
544	979091
545	934221
546	879335
547	460034
548	47397
549	540755
550	455678
551	398925
552	100328
553	817534
554	695344
555	44855
556	513434
557	334266
558	514696
559	201276
560	882391
561	67670
562	668427
563	900298
564	987477
565	604228
566	947222
567	979020
568	256954
569	981929
570	155723
571	141162
572	711604
573	535867
574	129665
575	768312
576	557535
577	10331
578	877633
579	531930
580	976868
581	699158
582	424408
583	937747
584	324933
585	627787
586	173451
587	366977
588	769304
589	796268
590	697305
591	372633
592	544372
593	510412
594	622150
595	865898
596	46444
597	508472
598	884345
599	14027
600	537182
601	685793
602	656754
603	504656
604	608227
605	349913
606	834723
607	219962
608	392369
609	121064
610	549739
611	736309
612	725976
613	930694
614	215323
615	570743
616	845800
617	350049
618	514270
619	719230
620	513859
621	165492
622	618024
623	948732
624	172424
625	36947
626	616039
627	875247
628	234826
629	620834
630	893924
631	99126
632	247899
633	163449
634	338603
635	395415
636	553426
637	247678
638	793362
639	699027
640	998649
641	480247
642	367316
643	859367
644	222412
645	27425
646	676149
647	382232
648	869309
649	766827
650	600883
651	808465
652	604133
653	40379
654	881326
655	77962
656	112366
657	397797
658	687831
659	131126
660	307579
661	273955
662	287380
663	126936
664	101731
665	874982
666	401743
667	550690
668	504740
669	163589
670	755593
671	354429
672	36314
673	291664
674	62294
675	282046
676	727026
677	689537
678	208082
679	384897
680	917680
681	625609
682	545483
683	486776
684	380827
685	906691
686	359385
687	12887
688	567893
689	675768
690	836768
691	21284
692	990774
693	121779
694	810107
695	820963
696	749757
697	522790
698	242753
699	454195
700	592891
701	11464
702	827681
703	828826
704	912968
705	564220
706	579465
707	466538
708	433941
709	192421
710	118837
711	68541
712	486887
713	283507
714	619101
715	729026
716	134019
717	701298
718	586175
719	19248
720	521258
721	805834
722	201582
723	242986
724	350894
725	244906
726	215270
727	442088
728	7159
729	975350
730	517383
731	734798
732	587091
733	771139
734	272119
735	581693
736	394746
737	642235
738	200631
739	704141
740	304342
741	58359
742	306104
743	532817
744	397029
745	541932
746	122352
747	665891
748	25051
749	819365
750	11576
751	838907
752	436754
753	476696
754	473300
755	369660
756	39288
757	981225
758	109334
759	162086
760	586841
761	626411
762	139745
763	676229
764	913508
765	151367
766	778
767	205116
768	608750
769	375183
770	88448
771	63111
772	921259
773	804523
774	310498
775	501384
776	810894
777	655414
778	348844
779	306501
780	425396
781	283120
782	425
783	993220
784	416613
785	998249
786	929572
787	684560
788	87440
789	265316
790	77275
791	253884
792	563033
793	527419
794	411851
795	567292
796	892799
797	695132
798	644648
799	5437
800	295017
801	275846
802	962258
803	177384
804	441616
805	11543
806	883880
807	188437
808	938322
809	973927
810	355443
811	338357
812	178724
813	889481
814	337808
815	798392
816	165461
817	235247
818	665647
819	601278
820	708993
821	6802
822	38352
823	248100
824	390929
825	294790
826	229384
827	403604
828	432345
829	408680
830	414114
831	317305
832	169509
833	275965
834	655502
835	748910
836	450481
837	908598
838	497527
839	319425
840	760375
841	721246
842	610087
843	874804
844	813797
845	163274
846	408368
847	93053
848	376750
849	650082
850	272675
851	894140
852	247419
853	546091
854	254029
855	454384
856	71417
857	435661
858	214233
859	499670
860	457953
861	759603
862	496518
863	414065
864	177674
865	94236
866	361745
867	734058
868	857597
869	916965
870	56286
871	956744
872	414228
873	195603
874	407534
875	219143
876	89888
877	824270
878	284146
879	501842
880	480096
881	396469
882	905985
883	244861
884	697348
885	25259
886	891572
887	711805
888	572286
889	781080
890	127914
891	693012
892	765797
893	842468
894	781798
895	303579
896	702737
897	70291
898	278946
899	943903
900	56255
901	17534
902	713080
903	190888
904	33275
905	828398
906	588683
907	261206
908	761186
909	385746
910	414035
911	794533
912	462079
913	821340
914	929736
915	595135
916	490865
917	134504
918	645733
919	13508
920	65941
921	361589
922	899382
923	227440
924	482182
925	735083
926	758845
927	520054
928	791171
929	499326
930	624318
931	706610
932	546737
933	872195
934	312863
935	702708
936	576785
937	423707
938	103159
939	416301
940	788795
941	628982
942	653935
943	788193
944	887580
945	911004
946	82236
947	787028
948	919251
949	527346
950	996263
951	952507
952	898660
953	424029
954	838987
955	954348
956	621805
957	816026
958	53671
959	359432
960	581403
961	195596
962	827043
963	928845
964	593903
965	741642
966	704787
967	267817
968	103311
969	70131
970	733627
971	817502
972	180558
973	276613
974	122683
975	523872
976	915288
977	858147
978	111837
979	854245
980	892423
981	925408
982	336037
983	737789
984	750702
985	355794
986	799314
987	624100
988	830640
989	540234
990	202801
991	867971
992	189650
993	110794
994	572360
995	563634
996	277996
997	808489
998	156888
999	69553

In [ ]:
def readpartition(table,partition):
    syntactic="select * from "+str(table)+str(partition)+" "
    cursor.execute(syntactic)
    result=cursor.fetchall()
    x= list(result)
    s = [[str(e) for e in row] for row in x]                     #Pretty printer
    lens = [max(map(len, col)) for col in zip(*s)]
    fmt = '\t'.join('{{:{}}}'.format(x) for x in lens)
    table = [fmt.format(*row) for row in s]
    print('\n'.join(table))

In [26]:
readpartition("CRIMMEO",4)

,DR_NO,Date_Rptd,DATE_OCC,TIME_OCC,AREA_,AREA_NAME,Rpt_Dist_No,Part_1-2,Crm_Cd,Crm_Cd_Desc,...,Status,Status_Desc,Crm_Cd1,Crm_Cd2,Crm_Cd3,Crm_Cd4,LOCATION,Cross_Street,LAT,LON
0,1307355,02/20/2010 12:00:00 AM,02/20/2010 12:00:00 AM,1350,13,Newton,1385,2,900,VIOLATION OF COURT ORDER,...,AA,Adult Arrest,900.0,NaN,NaN,NaN,300 E GAGE AV,NaN,33.9825,-118.2695
1,11401303,09/13/2010 12:00:00 AM,09/12/2010,45,14,Pacific,1485,2,740,"VANDALISM - FELONY ($400 & OVER, ALL CHURCH VA...",...,IC,Invest Cont,740.0,NaN,NaN,NaN,SEPULVEDA BL,MANCHESTER AV,33.9599,-118.3962
2,70309629,08/09/2010,08/09/2010,1515,13,Newton,1324,2,946,OTHER MISCELLANEOUS CRIME,...,IC,Invest Cont,946.0,NaN,NaN,NaN,1300 E 21ST ST,NaN,34.0224,-118.2524
3,90631215,01/05/2010,01/05/2010,150,6,Hollywood,646,2,900,VIOLATION OF COURT ORDER,...,IC,Invest Cont,900.0,998.0,NaN,NaN,CAHUENGA BL,HOLLYWOOD BL,34.1016,-118.3295
4,100100501,01/03/2010,01/02/2010,2100,1,Central,176,1,122,"RAPE, ATTEMPTED",...,IC,Invest Cont,122.0,NaN,NaN,NaN,8TH ST,SAN PEDRO ST,34.0387,-118.2488
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,100100835,04/17/2010 12:00:00 AM,04/17/2010 12:00:00 AM,2100,1,Central,158,1,230,"ASSAULT WITH DEADLY WEAPON, AGGRAVATED ASSAULT",...,IC,Invest Cont,230.0,NaN,NaN,NaN,6TH,CERES AV,34.0394,-118.2405
96,100100837,04/21/2010 12:00:00 AM,04/20/2010 12:00:00 AM,1800,1,Central,156,2,626,INTIMATE PARTNER - SIMPLE ASSAULT,...,AA,Adult Arrest,626.0,NaN,NaN,NaN,500 WALL ST,NaN,34.0449,-118.2458
97,100100838,04/21/2010 12:00:00 AM,04/20/2010 12:00:00 AM,1750,1,Central,156,2,626,INTIMATE PARTNER - SIMPLE ASSAULT,...,AA,Adult Arrest,626.0,NaN,NaN,NaN,500 WALL ST,NaN,34.0449,-118.2458
98,100100839,04/21/2010 12:00:00 AM,04/21/2010 12:00:00 AM,1230,1,Central,159,2,626,INTIMATE PARTNER - SIMPLE ASSAULT,...,IC,Invest Cont,626.0,NaN,NaN,NaN,7TH ST,MATEO ST,34.0346,-118.2323
99,100100842,04/24/2010 12:00:00 AM,04/24/2010 12:00:00 AM,100,1,Central,152,2,626,INTIMATE PARTNER - SIMPLE ASSAULT,...,IC,Invest Cont,626.0,NaN,NaN,NaN,800 WILSHIRE BL,NaN,34.0494,-118.2581

In [25]:
dataframe=pd.read_csv("Crime_Data_from_2010_to_2019.csv",encoding='unicode_escape')

In [24]:
import pandas as pd

In [ ]:
def enhancedreducer(table,attributelisttodisplay,attributestosearchby,attributevaluesforsearch):
    list_all=[]
    for i in range(len(attributestosearchby)):
        df=enhancedmapper(table,i,attributestosearchby[i],attributevaluesforsearch[i])
        list_all.append(df)
    df1=list_all[0]
    df2=list_all[1]
    D=pd.merge(df1, df2, how ='inner', on =['DR_NO', 'DR_NO'])
    for j in range(2,len(list_all)):
        df=list_all[j]
        D=pd.erge(D,df,how='inner',on=['DR_NO', 'DR_NO'])
    D=D[attributelisttodisplay]
    print(D)

In [ ]:
def enhancedmapper(table,i,attr,attrv):
    syntacting="select * from "+str(table)+" where "+str(attr)+" = "+str(attrv)
    dataframe=pd.read_sql(syntacting,con=connection)

In [31]:
table="CRIMEO"
attributestodisplay=['DR_NO','AREA_','AREA_NAME','Status_Desc']
attributestosearchby=['Crm_Cd','Vict_Age']
attributevaluesforsearch=['900','70']
enhancedreducer(table,attributelisttodisplay,attributestosearchby,attributevaluesforsearch)

             DR_NO  AREA_    AREA_NAME   Status_Desc
62879    100808022      8      West LA   Invest Cont
88463    101816984     18    Southeast   Adult Other
394822   110918996      9     Van Nuys   Invest Cont
478385   120405525      4   Hollenbeck   Invest Cont
661774   130817980      8      West LA   Invest Cont
673400   130415904      4   Hollenbeck  Adult Arrest
706431   130416018      4   Hollenbeck   Invest Cont
840519   141712947     17   Devonshire   Adult Other
900277   141308193     13       Newton   Invest Cont
929040   140315742      3    Southwest   Adult Other
944143   141916459     19      Mission   Invest Cont
948346   141715096     17   Devonshire   Invest Cont
952678   141515781     15  N Hollywood  Adult Arrest
1045362  150718221      7     Wilshire   Invest Cont

In [34]:
cat(CRIMEO,1000)

,DR_NO,Date_Rptd,DATE_OCC,TIME_OCC,AREA_,AREA_NAME,Rpt_Dist_No,Part_1-2,Crm_Cd,Crm_Cd_Desc,...,Status,Status_Desc,Crm_Cd1,Crm_Cd2,Crm_Cd3,Crm_Cd4,LOCATION,Cross_Street,LAT,LON
0,1307355,02/20/2010 12:00:00 AM,02/20/2010 12:00:00 AM,1350,13,Newton,1385,2,900,VIOLATION OF COURT ORDER,...,AA,Adult Arrest,900.0,NaN,NaN,NaN,300 E GAGE AV,NaN,33.9825,-118.2695
1,11401303,09/13/2010 12:00:00 AM,09/12/2010,45,14,Pacific,1485,2,740,"VANDALISM - FELONY ($400 & OVER, ALL CHURCH VA...",...,IC,Invest Cont,740.0,NaN,NaN,NaN,SEPULVEDA BL,MANCHESTER AV,33.9599,-118.3962
2,70309629,08/09/2010,08/09/2010,1515,13,Newton,1324,2,946,OTHER MISCELLANEOUS CRIME,...,IC,Invest Cont,946.0,NaN,NaN,NaN,1300 E 21ST ST,NaN,34.0224,-118.2524
3,90631215,01/05/2010,01/05/2010,150,6,Hollywood,646,2,900,VIOLATION OF COURT ORDER,...,IC,Invest Cont,900.0,998.0,NaN,NaN,CAHUENGA BL,HOLLYWOOD BL,34.1016,-118.3295
4,100100501,01/03/2010,01/02/2010,2100,1,Central,176,1,122,"RAPE, ATTEMPTED",...,IC,Invest Cont,122.0,NaN,NaN,NaN,8TH ST,SAN PEDRO ST,34.0387,-118.2488
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048541,150209582,04/14/2015 12:00:00 AM,00:00,2000,2,Rampart,241,2,740,"VANDALISM - FELONY ($400 & OVER, ALL CHURCH VA...",...,IC,Invest Cont,740.0,NaN,NaN,NaN,400 S LAFAYETTE PARK PL,NaN,34.0658,-118.2814
1048542,150907764,03/16/2015 12:00:00 AM,03/16/2015 12:00:00 AM,1530,9,Van Nuys,974,1,440,THEFT PLAIN - PETTY ($950 & UNDER),...,IC,Invest Cont,440.0,NaN,NaN,NaN,14600 VENTURA BL,NaN,34.1547,-118.4530
1048543,151009240,05/09/2015,04/15/2015 12:00:00 AM,1800,10,West Valley,1005,2,930,CRIMINAL THREATS - NO WEAPON DISPLAYED,...,AO,Adult Other,930.0,NaN,NaN,NaN,7900 WHITE OAK AV,NaN,34.2147,-118.5230
1048544,150906021,02/11/2015,00:00,305,9,Van Nuys,904,1,341,"THEFT-GRAND ($950.01 & OVER)EXCPT,GUNS,FOWL,LI...",...,IC,Invest Cont,341.0,NaN,NaN,NaN,15200 STAGG ST,NaN,34.2121,-118.4646
1048545,150411129,06/18/2015 12:00:00 AM,06/18/2015 12:00:00 AM,800,4,Hollenbeck,422,2,956,"LETTERS, LEWD - TELEPHONE CALLS, LEWD",...,AO,Adult Other,956.0,NaN,NaN,NaN,2300 GATES ST,NaN,34.0719,-118.2065

In [ ]:
def cat(table,partitions):
    sentence="select * from "+table+str(0)
    df1=pd.read_sql(sentence,con=connection)
    
    sentences="select * from "+table+str(1)
    df2=pd.read_sql(sentences,con=connection)

    dfinitial=pd.concat([df1,df2],axis=1)
    for i in range(2,partitions):
        sentence="select * from table"+str(i)
        dfe=pd.read_sql(sentence,con=connection)
        dfinitial=pd.concat([dfinitial,dfe],axis=1)
    print(dfinitial)

In [167]:
dataframe=pd.read_csv("CRIMEO.csv")

In [168]:
import pandas as pd

In [169]:
partiateddf=dataframe.iloc[0:200,:]

In [171]:
from pathlib import Path
filepath= Path('CRIMEO.csv')
filepath.parent.mkdir(parents=True, exist_ok=True)  
partiateddf.to_csv(filepath)

In [174]:
dfo=pd.read_csv("./CRIMEO.csv")

In [175]:
print(len(dfo))

200

In [30]:
df1 = pd.DataFrame({'lkey': ['foo', 'bar', 'baz', 'foo'],
                    'value': [1, 2, 3, 5]})
df2 = pd.DataFrame({'lkey': ['foo', 'bar', 'baz', 'foo'],
                    'value': [5, 6, 7, 8]})
df1

  lkey  value
0  foo      1
1  bar      2
2  baz      3
3  foo      5

In [31]:
df2

  lkey  value
0  foo      5
1  bar      6
2  baz      7
3  foo      8

In [32]:
df1.merge(df2, how='inner')

  lkey  value
0  foo      5

In [69]:
for i in range(9):
    print(i)

0
1
2
3
4
5
6
7
8